const ORACULO_MENSAGENS = [
    // --- MENSAGENS ESPECIAIS (FRASES DA TUA IRMÃ - POSIÇÕES 1 A 20) ---
    "Tens tentado fazer tudo certo, agradar toda a gente e evitar conflitos. Mas, no meio desse esforço, foste-te afastando de ti. Hoje faz uma pausa e pergunta-te uma coisa muito simples: “O que é que eu preciso?” Talvez seja a primeira vez, em muito tempo, que te permites ouvir essa resposta.",
    "Nem tudo o que te preocupa merece ocupar tanto espaço dentro de ti. Há pensamentos que se repetem tantas vezes que acabam por parecer verdade. Nem sempre são. Antes de continuares a alimentar esse peso, pergunta-te se ele pertence ao presente ou apenas a um medo antigo.",
    "Há pessoas que entram na nossa vida para caminhar ao nosso lado. Outras entram apenas para nos ensinar. Não confundas uma lição com um lugar onde tens de permanecer.",
    "Tens esperado sentir-te preparada para dar o próximo passo. Mas talvez nunca exista esse momento perfeito. Há caminhos que só se revelam quando começamos a andar.",
    "Hoje não te cobres tanto. Nem todos os dias são feitos para produzir, resolver ou conquistar. Alguns existem apenas para recuperar a energia que tens vindo a gastar sem perceber.",
    "Se continuas a voltar ao mesmo problema, talvez a vida não esteja a castigar-te. Talvez esteja apenas a mostrar-te uma lição que ainda não olhaste de frente.",
    "Nem tudo o que dói precisa de ser consertado imediatamente. Há feridas que cicatrizam melhor quando deixamos de lhes tocar todos os dias.",
    "Às vezes dizes “está tudo bem” tantas vezes que acabas por acreditar nisso. Hoje permite-te ser honesta contigo. Não precisas de estar sempre forte.",
    "Há uma diferença entre insistir e respeitar o teu próprio tempo. Nem sempre desistir significa perder. Às vezes significa escolher a tua paz.",
    "Se sentes que estás perdida, talvez não estejas. Talvez estejas apenas numa fase em que a tua vida já não combina com a pessoa que eras, mas ainda está a construir a pessoa que vais ser.",
    "Há uma conversa que tens evitado. Seja contigo ou com outra pessoa. Quanto mais a adias, mais espaço ela ocupa dentro de ti. Talvez hoje seja um bom dia para começar.",
    "Não tenhas medo de mudar de opinião. Crescer também é reconhecer que aquilo que fazia sentido ontem já não representa quem és hoje.",
    "Nem toda a gente vai compreender as decisões que estás a tomar. E está tudo bem. Nem todos conhecem a batalha que travaste para chegar até aqui.",
    "Talvez estejas tão focada naquilo que ainda falta que já não consegues ver tudo o que conseguiste construir. Respira. Olha para trás por um instante. Dá valor ao caminho que já percorreste.",
    "Se tens sentido vontade de recomeçar, não ignores esse impulso. Há fases da vida em que permanecer no mesmo lugar dói mais do que mudar.",
    "Não confundas paz com ausência de problemas. Paz é conseguires continuar a caminhar sem deixares que tudo o que acontece à tua volta determine aquilo que sentes por dentro.",
    "Hoje experimenta fazer menos uma coisa por obrigação e mais uma coisa por ti. Pequenas escolhas repetidas todos os dias acabam por transformar uma vida inteira.",
    "Há momentos em que procuramos respostas em toda a parte. Mas talvez a resposta que precisas esteja escondida na pergunta que tens medo de fazer a ti própria.",
    "Não desperdices energia a tentar convencer alguém do teu valor. Quem precisa de provas para te reconhecer dificilmente saberá cuidar daquilo que és.",
    "Se hoje sentes que nada está a acontecer, lembra-te de que as maiores mudanças raramente começam por fora. Primeiro reorganizam-se dentro de nós. Só depois começam a aparecer no mundo.",

    // --- MENSAGENS COMPLEMENTARES DE ELEVAÇÃO E CRISTAIS ---
    "Mesmo quando a tempestade parece longa, as tuas raízes estão a ficar mais fortes. Respira fundo: o sol da KOKARTE está a voltar a brilhar na tua vida.",
    "Tudo o que enfrentaste até aqui não veio para te parar, mas para te revelar a força imensa que carregas. Confia no processo da tua cura.",
    "O universo não erra o momento. Se estás a ler isto hoje, é porque a tua energia está pronta para libertar o passado e abraçar uma nova fase de prosperidade.",
    "A dor que sentiste no passado foi a preparação para a bênção que estás prestes a receber. Mantém o teu coração aberto e a tua intuição desperta.",
    "Ultrapassar momentos difíceis é a arte de transformar pedras em degraus. Estás mais perto da tua vitória do que imaginas.",
    "Permite-te desacelerar. O teu valor não está na pressa, mas na paz com que acolhes a tua própria jornada espiritual.",
    "Quando tudo parecer incerto, confia na sabedoria do silêncio. Um novo ciclo de clareza e luz está a começar para ti.",
    "A tua porta espiritual abre-se quando deixas de alimentar o medo e começas a confiar na luz que habita dentro de ti.",
    "Cada cristal guarda uma vibração única. Escolhe aquele que faz o teu coração sentir paz e deixa a sua energia acompanhar o teu caminho.",
    "Nem todas as respostas chegam de imediato. Algumas revelam-se quando a tua energia encontra o equilíbrio certo.",
    "O universo envia sinais todos os dias. Mantém a tua mente aberta e a tua intuição desperta.",
    "A ametista recorda-te que a serenidade é uma força poderosa. Respira fundo e permite que a paz te envolva.",
    "Quando limpas a energia da tua casa, também crias espaço para novas oportunidades entrarem na tua vida.",
    "Há portas espirituais que só se abrem quando deixas para trás aquilo que já não faz parte do teu destino.",
    "Confia na energia do momento presente. É nele que começam todas as grandes transformações.",
    "O quartzo transparente amplifica a tua intenção. Escolhe pensamentos de luz e deixa-os florescer.",
    "A tua alma conhece o caminho, mesmo quando a tua mente está cheia de dúvidas.",
    "Toda a energia que ofereces ao mundo regressa até ti multiplicada. Espalha luz sempre que puderes.",
    "Os cristais não mudam o teu destino; ajudam-te a recordar o poder que sempre existiu dentro de ti.",
    "A verdadeira prosperidade nasce quando o teu coração vibra em gratidão.",
    "A tua porta espiritual fortalece-se sempre que escolhes o amor em vez do medo.",
    "O universo trabalha em silêncio enquanto prepara a tua próxima vitória.",
    "Quando um ciclo termina, outro começa com possibilidades ainda maiores. Recebe essa mudança com confiança.",
    "A energia da lua convida-te a libertar o peso do passado e a renovar a tua essência.",
    "Cada passo consciente aproxima-te da versão mais luminosa de ti.",
    "Nem toda a batalha precisa de ser travada. Algumas dissolvem-se quando elevas a tua frequência.",
    "O cristal certo encontra sempre a pessoa certa no momento certo.",
    "Escuta a tua intuição. Ela fala baixinho, mas nunca se engana.",
    "A tua luz continua viva, mesmo nos dias em que não a consegues ver.",
    "Protege a tua energia da mesma forma que proteges o teu coração.",
    "O universo abre caminhos onde antes só conseguias ver obstáculos.",
    "Há uma bênção silenciosa a aproximar-se de ti. Mantém a tua fé viva.",
    "Cada cristal é um lembrete de que a natureza guarda uma sabedoria ancestral.",
    "A tua energia merece ambientes, pessoas e pensamentos que a façam crescer.",
    "Hoje pode ser o primeiro dia de uma transformação que vais agradecer no futuro.",
    "Liberta aquilo que pesa. A tua alma foi feita para voar, não para carregar correntes.",
    "Quando a tua vibração muda, o mundo à tua volta começa a responder de forma diferente.",
    "A porta espiritual da abundância abre-se através da gratidão diária.",
    "O quartzo rosa lembra-te que o amor-próprio é a base de todas as outras formas de amor.",
    "O equilíbrio começa quando deixas de lutar contra ti próprio.",
    "Toda a energia positiva que cultivas torna-se um farol para novas oportunidades.",
    "A tua essência é mais poderosa do que qualquer dificuldade temporária.",
    "O universo conhece sonhos que ainda nem tiveste coragem de revelar.",
    "A paz interior é o cristal mais raro que podes cultivar.",
    "Confia: aquilo que está destinado a ti encontrará sempre o caminho.",
    "A tua jornada espiritual não exige perfeição, apenas autenticidade.",
    "Os cristais acompanham-te como símbolos da intenção que colocas em cada novo dia.",
    "Há momentos em que fechar uma porta é exatamente o que permite abrir outra muito maior.",
    "A energia da gratidão transforma o comum em extraordinário.",
    "Permite que a luz substitua o medo e observa a transformação acontecer.",
    "Cada amanhecer traz consigo uma oportunidade para renovar a tua frequência.",
    "A tua força espiritual cresce sempre que escolhes continuar, mesmo sem ver o destino.",
    "A proteção começa quando acreditas no valor da tua própria energia.",
    "A abundância aproxima-se de quem vibra em amor, esperança e confiança.",
    "Não subestimes o poder de uma intenção colocada com verdade e coração.",
    "O universo está constantemente a conspirar para o teu crescimento, mesmo quando não consegues perceber.",
    "Que esta mensagem seja um sinal de que uma nova porta espiritual está prestes a abrir-se, trazendo paz, equilíbrio, proteção e novas energias para a tua vida.",
    "Sempre que um cristal chega até ti, é porque a tua alma está pronta para receber uma nova aprendizagem.",
    "A energia que procuras já vive dentro de ti. Os cristais apenas ajudam a despertá-la.",
    "A tua intuição é a chave que abre as portas espirituais mais importantes da tua vida.",
    "Cada desafio remove um bloqueio energético e aproxima-te da tua missão.",
    "O universo recompensa quem mantém a fé mesmo quando ainda não consegue ver o caminho.",
    "A luz que procuras nunca esteve longe. Ela sempre brilhou dentro do teu coração.",
    "Respira profundamente e entrega as tuas preocupações ao universo. A resposta chegará no momento certo.",
    "O cristal que hoje te chama pode ser exatamente aquele de que a tua energia precisa.",
    "Nada acontece por acaso. Cada encontro e cada despedida fazem parte da tua evolução espiritual.",
    "Quando escolhes viver em paz, atrais pessoas e oportunidades com a mesma frequência.",
    "Confia na proteção divina que acompanha cada passo da tua jornada.",
    "A tua vibração de hoje determina as oportunidades de amanhã.",
    "As portas da abundância começam a abrir-se quando libertas o medo da escassez.",
    "Cada novo amanhecer é uma oportunidade para renovar a tua energia e manifestar os teus sonhos."
];

// Dados das Energias dos 12 Meses (Automação de Janeiro a Dezembro)
const ENERGIAS_MESES = {
    0: { // Janeiro
        mes: "Janeiro — Energia da Renovação e Novos Começos",
        cristal: "Quartzo Transparente",
        beneficios: "Limpeza energética, clareza mental e definição de intenções elevadas.",
        cuidados: "Evita acumular sentimentos do ano passado. Deixa ir o que já não te serve.",
        afirmacao: "Eu abro os meus braços para as infinitas possibilidades de luz deste novo ciclo."
    },
    1: { // Fevereiro
        mes: "Fevereiro — Energia da Intuição e Conexão",
        cristal: "Ametista",
        beneficios: "Tranquilidade emocional, elevação espiritual e proteção contra energias densas.",
        cuidados: "Atenção ao desgaste mental. Reserva momentos diários para momentos de silêncio.",
        afirmacao: "A minha intuição é o meu guia sagrado. Eu escuto a sabedoria da minha alma."
    },
    2: { // Março
        mes: "Março — Energia do Equilíbrio e Cura",
        cristal: "Quartzo Verde",
        beneficios: "Vitalidade física, harmonização do chakra cardíaco e regeneração de forças.",
        cuidados: "Não guardes ressentimentos. A cura começa quando perdoas a ti e aos outros.",
        afirmacao: "A minha vida flui em perfeita harmonia, saúde e amor incondicional."
    },
    3: { // Abril
        mes: "Abril — Energia da Força e Foco",
        cristal: "Olho de Tigre",
        beneficios: "Proteção espiritual, coragem para ultrapassar obstáculos e foco nos objetivos.",
        cuidados: "Cuidado com o excesso de autocrítica. Reconhece cada pequeno avanço teu.",
        afirmacao: "Eu sou forte, protegido(a) e capaz de vencer qualquer desafio com sabedoria."
    },
    4: { // Maio
        mes: "Maio — Energia do Amor Próprio e Acolhimento",
        cristal: "Quartzo Rosa",
        beneficios: "Abertura para o amor, pacificação de mágoas e fortalecimento da autoestima.",
        cuidados: "Evita procurar validação externa. O amor mais profundo nasce dentro de ti.",
        afirmacao: "Eu mereço todo o amor, respeito e abundância que o universo tem para me dar."
    },
    5: { // Junho
        mes: "Junho — Energia da Prosperidade e Luz Solar",
        cristal: "Citrino",
        beneficios: "Alegria de viver, atração de abundância e desbloqueio da criatividade.",
        cuidados: "Cuidado com pensamentos de escassez. Foca na gratidão do que já conquistaste.",
        afirmacao: "A minha energia é radiante como o sol. Eu atraio prosperidade em todas as áreas."
    },
    6: { // Julho
        mes: "Julho — Energia da Proteção e Ancoramento",
        cristal: "Turmalina Negra",
        beneficios: "Escudo contra inveja e maus-olhados, estabilidade emocional e enraizamento.",
        cuidados: "Protege o teu campo energético de conversas negativas ou ambientes pesados.",
        afirmacao: "Eu estou profundamente protegido(a), centrado(a) e seguro(a) na minha luz."
    },
    7: { // Agosto
        mes: "Agosto — Energia da Sabedoria e Expressão",
        cristal: "Lápis-Lazúli",
        beneficios: "Clareza na comunicação, paz interior e despertar da sabedoria ancestral.",
        cuidados: "Não te cales por medo do julgamento. A tua verdade é valiosa.",
        afirmacao: "Eu expresso a minha verdade com amor, firmeza e sabedoria."
    },
    8: { // Setembro
        mes: "Setembro — Energia da Colheita e Gratidão",
        cristal: "Cornalina",
        beneficios: "Motivação, coragem para agir e celebração das tuas conquistas.",
        cuidados: "Evita a procrastinação. Dá o primeiro passo, mesmo que pareça pequeno.",
        afirmacao: "Eu colho com gratidão os frutos do meu trabalho e da minha dedicação."
    },
    9: { // Outubro
        mes: "Outubro — Energia da Transformação",
        cristal: "Obsidiana",
        beneficios: "Libertação de bloqueios profundos, transformação pessoal e coragem espiritual.",
        cuidados: "Não tenhas medo da mudança. O fim de um ciclo é o início de algo maior.",
        afirmacao: "Eu liberto o passado com gratidão e acolho a minha melhor versão."
    },
    10: { // Novembro
        mes: "Novembro — Energia da Paz e Espiritualidade",
        cristal: "Selenita",
        beneficios: "Purificação de ambientes, elevação vibracional e conexão angelical.",
        cuidados: "Evita confusões ou correrias desnecessárias. Procura momentos de serenidade.",
        afirmacao: "A minha mente está em paz e o meu espírito conectado com a luz divina."
    },
    11: { // Dezembro
        mes: "Dezembro — Energia da Celebração e Encerramento",
        cristal: "Pedra do Sol",
        beneficios: "Sentimento de dever cumprido, calor humano e renovação das esperanças.",
        cuidados: "Evita o cansaço extremo nas festividades. Prioriza o teu descanso.",
        afirmacao: "Eu celebro a minha caminhada e recebo a nova fase com o coração cheio de luz."
    }
};